pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
          [key: 'action', value: '$.action'],
          [key: 'ref', value: '$.pull_request.base.ref']
      ],
     causeString: 'Webhook PR triggered ($action) in branch $ref',
     token: '123456',
     tokenCredentialId: '',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: false,
     shouldNotFlatten: false
    )
  }
  stages {
    stage('Run Terraform Code On Pipeline 2') {
      steps {
        git branch: [[name: 'ref']],
          credentialsId: '1b750a46-d671-426e-88af-8c14d18db341',
          url: 'https://github.com/ADCREW-LLC/khiem-dc11-terraform.git'
        sh "ls -lat"
        sh "terraform fmt"
        sh "terraform init -reconfigure"
        sh "terraform validate && terraform apply -auto-approve"
      }
    }
  }
}
