pipeline {
  agent any
  triggers {
   GenericTrigger(
      genericVariables: [
             [ key: 'action',  value: '$.action'],
             [ key: 'draft_pr', value: '$.pull_request.draft'],
             [ key: 'pr_url', value: '$.pull_request.html_url'], 
             [ key: 'git_sha_statuses_url', value:
         '$.pull_request.statuses_url']      
      ],
      causeString: 'Triggered from PR: $pr_url',
      token: '123456',
      printContributedVariables: true,
      printPostContent: true,
      silentResponse: false,
      regexpFilterText: '$action#$draft_pr',
      regexpFilterExpression:  
         '(reopened|opened|synchronize|ready_for_review)#(false)'
     )
   }
  stages {
    stage('Run Terraform Code On Pipeline 2') {
      steps {
        git branch: 'main',
          credentialsId: '1b750a46-d671-426e-88af-8c14d18db341',
          url: 'https://github.com/ADCREW-LLC/khiem-dc11-terraform.git'
        sh "ls -lat"
        sh "terraform fmt"
        sh "terraform init -reconfigure"
        sh "terraform validate && terraform apply -auto-approve"
      }
    }
  }
}
