pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
          [key: 'ref', value: '$.ref'],
          [key: 'commit_titles', value: '$.commits[*].title']
      ],
     causeString: 'Webhook triggered because of $commit_titles in branch $ref',
     token: '123456',
     tokenCredentialId: '',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: false,
     shouldNotFlatten: false,
     regexpFilterText: 'BRANCH: $ref COMMIT_TITLES: $commit_titles END',
     regexpFilterExpression: "BRANCH: refs/heads/main COMMIT_TITLES .*?(Merge pull request).*? END"
    )
  }
  stages {
    stage('Run Terraform Code On Pipeline 2') {
      steps {
        git branch: 'main',
          credentialsId: '1b750a46-d671-426e-88af-8c14d18db341',
          url: 'https://github.com/ADCREW-LLC/khiem-dc11-terraform.git'
        sh "ls -lat"
        sh "terraform fmt"
        sh "terraform init -reconfigure"
        sh "terraform validate && terraform apply -auto-approve"
      }
    }
  }
}
