pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
          [key: 'action', value: '$.action'],
          [key: 'ref', value: '$.pull_request.base.ref']
      ],
     causeString: 'Webhook PR triggered ($action) in branch $ref',
     token: '123456'
    )
  }
  stages {
    stage('Run Terraform Code On Pipeline 1') {
      steps {
        git branch: '$ref',
          credentialsId: '1b750a46-d671-426e-88af-8c14d18db341',
          url: 'https://github.com/ADCREW-LLC/khiem-dc11-terraform.git'
        sh "ls -lat"
        script {
           GIT_COMMIT_EMAIL = sh (
                script: 'git --no-pager show -s --format=\'%ae\'',
                returnStdout: true
            ).trim()
            echo "Git committer email: ${GIT_COMMIT_EMAIL}"
        }
        sh "terraform fmt"
        sh "terraform init -reconfigure"
        sh "terraform validate"
        script {
          TERRAFORM_PLAN_OUTPUT = sh (
              script: 'terraform plan',
              returnStdout: true
          ).trim()
        }
        emailext body: TERRAFORM_PLAN_OUTPUT,
          subject: 'TERRAFORM_PLAN_OUTPUT',
          to: GIT_COMMIT_EMAIL
      }
    }
  }
}
